export const games = [
    {
        header: "https://img.itch.zone/aW1nLzI0NDE3MTg2LnBuZw==/347x500/5ou8y%2F.png",
        name: "Tower of Judgement",
        authors: [
            "Ricardo Morales Vargas",
            "Justin Plamo",
            "Thien Tran",
            "Viet Nguyen",
            "Zach Grant",
            "Sultan Sadiq",
            "Arturo Murga",
            "Shaheer Ismail",
        ],
        desc: "Tower of Judgement is a 2D top-down action-adventure game with hack-and-slash combat and retro 16-bit pixel art built in Unity for PC.",
        href: "https://goldengoosegames.itch.io/tower-of-judgement",
    },
    {
        header: "https://i.ytimg.com/vi_webp/7TMIgWTM3do/maxresdefault.webp",
        name: "The Tides of Andunië",
        authors: [
            "Timothy (Hayden) Groh",
            "Gustavo Buenrostro",
            "Alexis Orellana",
            "Trevor Topolski",
            "Mohamed Abdelrahman",
            "Tasneem Harianawala",
            "Darryl Sims",
            "Jason Vu",
        ],
        desc: "The Tides of Andunië is a top-down action RPG. Drop into a Tolkien-inspired world to defeat the pirates and save the Island of Erressëa.",
        href: "https://nospoonstudio.itch.io/the-tides-of-andunie"
    },
    {
        header: "https://img.itch.zone/aW1nLzI0NDU2MjQ4LnBuZw==/347x500/%2Fw0xoq.png",
        name: "Wild Pete",
        authors: [
            "Joseph Giap",
            "Emma Nguyen",
            "Cody Luc",
            "Johann Perez",
            "Thu Pham",
            "Angel Savaria",
            "Yousif Saieb",
        ],
        desc: "A pixel-art side scrolling combat game, where you must escape and fight through the prison to escape!",
        href: "https://josephgiap123.itch.io/wild-pete",
    },
    {
        header: "https://img.itch.zone/aW1nLzI0NDc5NTE2LnBuZw==/original/Z3%2FeBI.png",
        name: "Luminescence",
        authors: [
            "Kyle Lumbo",
            "Nathaniel McAndrews",
            "Paulo Cataquis",
            "Tadiwa Kabayadondo",
            "Zachary Ellerbrock",
            "Joseph Guzman",
            "Sergio Ramirez",
            "Tran Minh Tuong",
        ],
        desc: "Venture into the shadowed world of Lumen. Battle nightmarish creatures and survive the darkness, as you descend deeper into the abyss, searching to revive the last source of luminescence, in this epic 2D top down action adventure RPG.",
        href: "https://radiantstudios.itch.io/luminescence",
    },
    {
        header: "https://img.itch.zone/aW1nLzI0NjkyMDEyLnBuZw==/315x250%23c/0cDY%2Fu.png",
        name: "Rhythm Bells",
        href: "https://agwar.itch.io/rhythm-bells"
    },
    {
        header: "https://img.itch.zone/aW1nLzI0NzAyNTAzLnBuZw==/315x250%23c/ycuLoF.png",
        name: "Stealing Christmas",
        href: "https://junior4144.itch.io/stealing-christmas",
    },
]
